
export const metadata = {
    title: "Gautam's App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>this is conact page layout page{children}</body>
      </html>
    );
  }
  